### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by Martin-Pitt** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#11]
I was running through the whole official "Quick Start" guide, but ran into numerous issues.

Being suspicious of one of the error messages, I notice that the guide is out of date in comparison to the main branch here.

https://docs.microsoft.com/en-gb/azure/active-directory/develop/active-directory-v2-devquickstarts-node-web

**Comment by jmprieur** [comment]
@navyasric : can you please have a look?

**Comment by navyasric** [comment]
@Martin-Pitt The docs link of the guide above now points to the master branch of this sample which is updated. Please try and reopen if you find issues. Thanks.
