### ISSUE TITLE
Access Token?

### ISSUE THREAD

**Issue by Martin-Pitt** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#12]
So logging in is all fine and dandy.

But how do I actually run queries against the Microsoft Graph API? It's unclear how to move forward.
How do I pass access token to use in requests?

I see the accessToken parameter in the 'verify' function callback. But how do I link it to the user session? Do I just inject it into the profile object?

Do I have to create a ES6 WeakMap to link the profile objects against the access tokens?

**Comment by lovemaths** [comment]
@Martin-Pitt 
(1) We currently only support getting access token. You can provide the Graph API you want in `scope` in config.js. After you run `passport.authenticate`, you will get the corresponding access token in the `verify` function. See https://github.com/AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs/blob/master/config.js#L56

(2) To get resource using access token, you can refer to Adal-node library (https://github.com/AzureAD/azure-activedirectory-library-for-nodejs)

(3) Yes, injecting the access token into the profile object would work.

**Comment by navyasric** [comment]
Closing as the issue seems answered in above comment
