### ISSUE TITLE
localhost unexpectedly closed the connection.

### ISSUE THREAD

**Issue by naveen26246** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#14]
Hi, 
I was trying out the node-js sample mentioned in **_https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-devquickstarts-node-web_**

However after entering my credentials, I am being redirected to https://localhost:3000/auth/openid/return with the following error: 'localhost unexpectedly closed the connection.'

Any leads to tackle the issue would be greatly appreciated. 

Thanks,
Naveen

**Comment by navyasric** [comment]
The link above now points to the master branch of this sample which has been updated. Please try and reopen if you still encounter an issue.
