### ISSUE TITLE
User Always Authenticated Despite Expired Token

### ISSUE THREAD

**Issue by MarkHerhold** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#16]
I believe this project has an issue where users who authenticated once are always authenticated even after the token expires.

In the example code, middleware checks to see if the user is logged in and calls ([`req.isAuthenticated()`](https://github.com/AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs/blob/48c642bbdf51a5fc950d9eab645df8e0ad045aba/app.js#L192)) which always returns true.

This is demonstrable by navigating to `http://localhost:3000/account` two hours after first logging in and observing that the token expiration timestamp has passed, yet I am able to navigate to the `/account` page. Furthermore, this application does not appear to attempt to login again or refresh the token.

```
\"exp\":1514921200
```

**Versions:**
`AppModelv2-WebApp-OpenIDConnect-nodejs`: `48c642bbdf51a5fc950d9eab645df8e0ad045aba`
`passport-azure-ad` dependency: `3.0.9` (latest)

**Config:**
```js
exports.creds = {
identityMetadata: 'https://login.microsoftonline.com/[redacted].onmicrosoft.com/v2.0/.well-known/openid-configuration', 
  clientID: '[redacted]',
  responseType: 'id_token', 
  responseMode: 'form_post', 
  redirectUrl: 'http://localhost:3000/auth/openid/return', 
  allowHttpForRedirectUrl: true,
  clientSecret: '<your_client_secret>', 
  validateIssuer: true,
  issuer: null,
  passReqToCallback: false,
  useCookieInsteadOfSession: true,
  cookieEncryptionKeys: [ 
    { 'key': '12345678901234567890123456789012', 'iv': '123456789012' },
    { 'key': 'abcdefghijklmnopqrstuvwxyzabcdef', 'iv': 'abcdefghijkl' }
  ],
  scope: [],
  loggingLevel: 'info',
  nonceLifetime: null,
  nonceMaxAmount: 5,
  clockSkew: null,
};

post_logout_redirect_uri=http://localhost:3000';
exports.useMongoDBSessionStore = false;
exports.databaseUri = 'mongodb://localhost/OIDCStrategy';
exports.mongoDBSessionMaxAge = 24 * 60 * 60;  // 1 day (unit is second)
```

**Comment by lovemaths** [comment]
@MarkHerhold This is the correct behavior of passport.js framework. User info is extracted from the token and saved in session when user logs in for the first time. Note that token is only used once. For every subsequent request, Passport.js retrieves user info from session and assigns it to req.user. Whether a user is authenticated or not solely relies on the existence of req.user. As long as you have a valid session, you are always logged in. If you want to set an expiration time, you can either set an expiration time for cookie/session, or manually call req.logout() to delete the user from session after some time.

**Comment by MarkHerhold** [comment]
@lovemaths Thanks for the explanation. I take it that this token is just an `id_token`, correct? If so, is this project just performing an implicit grant auth flow?

**Comment by lovemaths** [comment]
@MarkHerhold Yes we use `id_token` for user info.  We support `id_token`, `code`, `code id_token` response types, for the latter two response types you will get access/refresh token as well. We don't do anything to access/refresh token, we just pass them to developer in the verify callback. If access token is expired, developer can call `passport.authenticate` to get a new one, or write their own code to apply the refresh token to get a new one.
