### ISSUE TITLE
git clone command wrong in README.md

### ISSUE THREAD

**Issue by SymmetricDesigns** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#19]
The clone command in README.md doesn't work (OS X).  I needed to change it to:
`git clone https://github.com/AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs.git`

**Comment by jmprieur** [comment]
Thanks @SymmetricDesigns. Fixed
cc: @navyasric
