### ISSUE TITLE
the nodejs web app deployed as azure app not working, getting error while authentication through Azure AD

### ISSUE THREAD

**Issue by luckyhegde** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#21]
Ive Deployed the Node js web app as  .azurewebsites.net , while connecting to the graph getting errors like invalid request with & unable to validate token. Please help or suggest how to deploy the nodejs app to azuresite

**Comment by jmprieur** [comment]
@navyasric : we might want to discuss about using the Readme template used in most samples (which also has a section for deploying to Azure)

**Comment by navyasric** [comment]
@luckyhegde Do you still have this issue? This sample only demonstrates OIDC sign in and does not call graph. Can you provide further details or code snippets of how you are connecting to graph if you need further assistance.

**Comment by suparnavg** [comment]
@navyasric could you please clarify something for me? My existing web application (registered on the [App Registration Portal](apps.dev.microsoft.com)) works fine if xyz@outlook.com users are trying to sign in using OIDC.

However if a user from an Azure AD tenant tries to sign in, an id_token is not returned in the OIDC token API call. Naturally their token cannot be validated and the log in fails.

Could you please clarify if I need to register an app on the App Registration Portal for all @outlook.com users and a SEPARATE APP on the Azure Portal for all other tenants? (I expect users from multiple tenants to sign up). Sorry to ask this here but there's a LOT of information (some conflicting) available on the Microsoft docs, and it's hard to get a single source of the latest and most correct information.

Edit: For example, [this page](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial), updated on Apr 18, 2018 says that separate app creation in Azure AD is NOT necessary.

> To build an app that accepts both personal Microsoft account (MSA) & work or school account (Azure AD) sign-in, you'll first need to register an app with Microsoft. At this time, you won't be able to use any existing apps you may have with Azure AD or MSA - you'll need to create a brand new one.

However [this page](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v1-integrate-apps-with-azure-ad), updated on Aug 28 2018 says that a SEPARATE APP must be registered in the Azure Portal

> Enterprise developers and software-as-a-service (SaaS) providers can develop commercial cloud services or line-of-business applications, that can be integrated with Azure Active Directory (Azure AD) to provide secure sign-in and authorization for their services. To integrate an application or service with Azure AD, a developer must first register the application with Azure AD.


Please help!

Edit2: the link "[About Delegated Permissions](apps.dev.microsoft.com)" on the App Registration Portal has no information about delegated permissions (or even the word "delegated"). Adding this here as an example of how confusing the documentation is.

**Comment by jmprieur** [comment]
Closing as we are archiving this sample
