### ISSUE TITLE
failed to generate PEM key due to: a key with the specific kid cannot be found

### ISSUE THREAD

**Issue by stevenkaspar** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#23]
Trying to run example as-is and I get the error

```
failed to generate PEM key due to: a key with the specific kid cannot be found
```

I was also stuck on this error following the setup in `passport-azure-ad`... not sure what to check

Any suggestions?

**Comment by jmprieur** [comment]
Closing as we are archiving this sample

**Comment by lingmaomao** [comment]
Anyone know why?
