### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by mvalin** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#29]
Hi,
 
I'm new working with Azure and NodeJS and I configure this the App on Azure but when I tried I get this error on the logs:
{"name":"AzureAD: Metadata Parser","hostname":"vmax-rog","pid":898,"level":50,"msg":"cannot get AAD Federation metadata from endpoint you specified","time":"2019-07-26T16:26:10.978Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"vmax-rog","pid":898,"level":50,"msg":"cannot get AAD Federation metadata from endpoint you specified","time":"2019-07-26T16:26:10.978Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"vmax-rog","pid":898,"level":30,"msg":"authentication failed due to: Cannot get AAD Federation metadata","time":"2019-07-26T16:26:10.988Z","v":0}
 
This is my second registration I did previously in another subscription and everything was fine, everything works but in this subscription I can get this example working, do you have any idea why is that? Can you give any advice to solve that?

Regards

**Comment by julie-ng** [comment]
### Cause - incorrect endpoint

The `identityMetadata` in  `config.js` no **line 3** is incorrect:

``` 
https://login.microsoftonline.com/<tenant_name>.onmicrosoft.com/v2.0/.well-known/openid-configuration
```

#### Correct URL Format

Without Tenant ID

```
https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration
```
With Tenant ID
```
https://login.microsoftonline.com/{{ TENANT_ID }}/v2.0/.well-known/openid-configuration
```

It might not be the only outdated endpoint. If you have a tenant, you can find the latest one in **Azure Portal**

Azure Active Directory > App Registrations > Endpoints

<img width="664" alt="Screen Shot 2019-09-29 at 10 07 46" src="https://user-images.githubusercontent.com/1269507/65829085-ce48cb80-e2a1-11e9-81e0-b1de780353bd.png">

/cc @jmprieur

**Comment by mvalin** [comment]
Hi @julie-ng ,

That was the solution that we applied, sorry but we didn't confirm here the solution, thank you for you message, that reminded me to update here.

Thank you.

**Comment by julie-ng** [comment]
You should consider leaving it open though because the code is still wrong and you are probably not the only person who will run into this problem

**Comment by mvalin** [comment]
Well, you have right, thank for bringing this to my mind.

I didn't think about that, as it is an example I didn't realize that they should fix this, but it would be very helpful for others, I will re-open the case and wait if someone takes this and solves the code.

As the solution is almost complete.

Regards

**Comment by jmprieur** [comment]
Closing as we are archiving this sample
