### ISSUE TITLE
Missing Commas

### ISSUE THREAD

**Issue by pbriggeman** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#3]
The current codebase errors on Node build because there are two commas missing:

config.js / line 10 should be:  responseMode: 'form_post',

app.js / line 88 should be: skipUserProfile: config.creds.skipUserProfile,

Note:  Had to change the scope in config.js to just 'profile' to get the application to work completely.

Other than these few things, fine job!  Thank you for posting the quick starter example.

**Comment by XavG** [comment]
Still not corrected !!!
Thanks pbriggeman

**Comment by luckyabhishek** [comment]
Still not corrected !!!
