### ISSUE TITLE
Requires permission to "Read your mail"

### ISSUE THREAD

**Issue by chriszrc** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#31]
Following the instructions from this sample repo, when I try the login, I'm prompted with the following message:

<img width="445" alt="ms_read_your_mail_permission" src="https://user-images.githubusercontent.com/25695785/66327685-3712f200-e8f9-11e9-9a50-8a9271caaefd.png">

I am using the "common" endpoint (`https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`). I have not added any additional api permissions, the only permission that is listed for this app registration is "User.Read". 

I don't want to require this permission just to use this service for handling authentication, is there a way to fix this?

**Comment by jmprieur** [comment]
Closing as we are archiving this sample
