### ISSUE TITLE
Sample is not SameSite cookie compliant

### ISSUE THREAD

**Issue by jeffwilcox** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#37]
Hi,
I was interested in experimenting with `SameSite` on the cookie, and this example, but it needs to do user agent sniffing, I believe, which can make it hard to dynamically change the cookie settings in Express, I believe.

Looking for guidance, or an update to the app, and happy to contribute, if someone can help brainstorm the appropriate work to be done here. I want to make sure my OpenID Connect `form_post` experience will continue to work in the new SameSite work.

**Comment by mvrak** [comment]
The new MSAL Node is now in preview.  It has samples and a quickstart that handle samesite.
We have several samples here for specific auth flows:
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/standalone-samples
And a published quickstart:
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-nodejs-webapp-msal

**Comment by derisen** [comment]
Closing as no further action to take.
