### ISSUE TITLE
App registration logout requires HTTPS URI but code sample doesn't support HTTPS

### ISSUE THREAD

**Issue by diberry** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#44]
How did you configure your app registration logout URI so that the local URI doesn't require HTTPS? I keep getting an error. If it must require the URI to support HTTPS, can you change the sample to also support that?

**Comment by derisen** [comment]
@diberry I think `http` scheme for logout URI was allowed when entered via the app manifest, but looks like that's no longer the case. So now the app needs to [create a https server](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/certificate-credentials.md#creating-an-https-server) to use the single sign-out feature. I don't have a solution at hand yet, but I'll put this in the backlog.

**Comment by derisen** [comment]
Closing this as we are archiving the sample. Please refer to the new sample using MSAL Node: https://github.com/Azure-Samples/ms-identity-node
