### ISSUE TITLE
[discussion] Protect my Node/Express routes on-premise?

### ISSUE THREAD

**Issue by RayDeanTech** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#45]
I'm trying to wrap my head around all this.  Can somebody at Microsoft make a YouTube video about this, but explained in a manner similar to how Richard Feynman explains physics (for the common Web/Backend Developer)?  I'm struggling to find a really decent example of how to bring this all together.

1. Is this sample "good enough" for me to protect my Node/Express routes?
2. Our Frontend is all vanilla JS (and jQuery) --- Is the idea that I can somehow use the browser for authN to store a token via a cookie, or something?  Then, that token is used on the backend for authZ?  Am I supposed to be using a Frontend framework like Angular/VUE/React to facilitate all this?
3. Do I use ODIC for the Frontend, and then "bearer tokens" on the Backend?  
4. How do I get a user's security group information?  I want to use this to control access to routes.  Like, if the user is in a "view only" group, obviously, they should only have Select, and not Create/Update/Delete, etc.

- Frontend:  jQuery/JavaScript, all manual, no front-end framework, no login buttons at the moment
- Backend:  Node/Express + MSSQL.  I want to use MSSQL to store session info if required, not MongoDB.
- Our AD is available on-premise, but I also have the ability to register apps in the Azure portal.

**Comment by derisen** [comment]
> I'm trying to wrap my head around all this. Can somebody at Microsoft make a YouTube video about this, but explained in a manner similar to how Richard Feynman explains physics (for the common Web/Backend Developer)? I'm struggling to find a really decent example of how to bring this all together.

I hear you -authentication is not easy :D

> 1. Is this sample "good enough" for me to protect my Node/Express routes?

This sample does no resource protection. It only enables a user to securely obtain access tokens, but it doesn't protect any data (that's bearer token scenarios)

> 2. Our Frontend is all vanilla JS (and jQuery) --- Is the idea that I can somehow use the browser for authN to store a token via a cookie, or something?  Then, that token is used on the backend for authZ?  Am I supposed to be using a Frontend framework like Angular/VUE/React to facilitate all this?

Yes, more or less. You don't need to use a framework though. And Passport.js won't help you on apps running on browser. I would recommend using [msal.js](https://github.com/AzureAD/microsoft-authentication-library-for-js) in the frontend. 

In addition, I would recommend going through [this tutorial](https://github.com/Azure-Samples/ms-identity-javascript-tutorial), it should help with most of your questions.

> 3. Do I use ODIC for the Frontend, and then "bearer tokens" on the Backend?

Roughly, yes (of course you can use OIDC on backend as well e.g. a web app that signs in users). Rather, OIDC is for authenticating a user and for acquiring access tokens for that user. Bearer tokens are for accessing a protected resource, e.g. a web API that requires a valid access token before responding to user's request to access her profile info.

> 4. How do I get a user's security group information?  I want to use this to control access to routes.  Like, if the user is in a "view only" group, obviously, they should only have Select, and not Create/Update/Delete, etc.

Check out either of these tutorials:

* In [React + Node.js](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/5-AccessControl/2-call-api-groups)
* In [Angular + .NET](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/5-AccessControl/2-call-api-groups)

> * Frontend:  jQuery/JavaScript, all manual, no front-end framework, no login buttons at the moment

That's fine.

> * Backend:  Node/Express + MSSQL.  I want to use MSSQL to store session info if required, not MongoDB.

That's fine too. express-session has connectors for mssql. Check [here](https://github.com/expressjs/session#compatible-session-stores)

> * Our AD is available on-premise, but I also have the ability to register apps in the Azure portal.

[msal.js](https://github.com/AzureAD/microsoft-authentication-library-for-js) supports ADFS 2019, but I don't have a good tutorial to offer to you.

**Comment by RayDeanTech** [comment]
I sincerely appreciate your replies.  Thank you!!!

**Comment by derisen** [comment]
My pleasure! Closing this then.
