### ISSUE TITLE
[quick fix] typo in app.js, line 165-ish

### ISSUE THREAD

**Issue by RayDeanTech** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#46]
IMHO, app.js line 165-ish should probably be `expressSession` instead of `express.session`, as shown in the screenshot below.  Otherwise, I don't think the middleware gets instantiated correctly, and it throws this error:

`Error: Most middleware (like session) is no longer bundled with Express and must be installed separately.`

![image](https://user-images.githubusercontent.com/21373144/126542403-601906ac-6c9a-4f58-bc72-ad3cc70aae00.png)

![image](https://user-images.githubusercontent.com/21373144/126542002-09212078-1508-4a13-95b9-35138d832d56.png)

**Comment by derisen** [comment]
@NamedArray good catch! We'll make sure to update, but feel free to create a PR
