### ISSUE TITLE
What are the prerequisites for `bunyan`?

### ISSUE THREAD

**Issue by RayDeanTech** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#47]
Is Python required to use `bunyan` in this example?  Is there an alternative for this output logger which does not require Python?

I can't tell if it actually was installed, or if it is working, as I'm able to run `node app.js | bunyan` without a problem...

![image](https://user-images.githubusercontent.com/21373144/126544491-827ad4e2-c45b-4389-90b9-72e78e527552.png)

**Comment by derisen** [comment]
@NamedArray I believe so, yes. bunyan is only for logging though, feel free to remove it or replace with an alternative (like [winston](https://www.npmjs.com/package/winston))
