### ISSUE TITLE
Why use process.nextTick ?

### ISSUE THREAD

**Issue by alexnix** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#48]
https://github.com/AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs/blob/f037b4651b4b93b80f405b703f6d2df2deb7e32a/app.js#L128

Can you please elaborate this?
I understand what nextTick does (https://nodejs.dev/learn/understanding-process-nexttick), but why use it here?

**Comment by derisen** [comment]
Apologies as this went unattended for so long. `process.nextTick` here is used to simulate an async operation.

Closing this as we are archiving the sample. Please refer to the new sample using MSAL Node: https://github.com/Azure-Samples/ms-identity-node
