### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by ToExperienceMore** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#51]
I finished the configure process as Readme. 
authentication failed due to: Cannot get AAD Federation metadata

**Comment by derisen** [comment]
Apologies as this went unattended for so long. Closing this as we are archiving the sample. Please refer to the new sample using MSAL Node: https://github.com/Azure-Samples/ms-identity-node
