### ISSUE TITLE
This example doesn't work as-is

### ISSUE THREAD

**Issue by HSAR** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#7]
I cloned this repository and went through the quick-start guide, replacing all the relevant fields in config.js (clientId, clientSecret and identityMetadata). The profile object passed via callback from a successful authentication was just fields with undefined values - "oid" being one of them, causing the example to fail.

I fixed this by changing the scope to ['profile'].

**Comment by lovemaths** [comment]
@HSAR Thank you, I included the fix in master branch.
